# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"B\n\x0c\x42uildRequest\x12\"\n\nembeddings\x18\x01 \x03(\x0b\x32\x0e.search.Vector\x12\x0e\n\x06\x61ppend\x18\x02 \x01(\x08\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"H\n\rBuildResponse\x12\x15\n\rtotal_vectors\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"i\n\x0cQueryRequest\x12$\n\x0cquery_vector\x18\x01 \x01(\x0b\x32\x0e.search.Vector\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x16\n\x0ereweight_iters\x18\x03 \x01(\x05\x12\x10\n\x08query_id\x18\x04 \x01(\t\"l\n\rQueryResponse\x12\x0f\n\x07indices\x18\x01 \x03(\x05\x12\x0e\n\x06scores\x18\x02 \x03(\x02\x12\x14\n\x0crecall_at_10\x18\x03 \x01(\x02\x12\x12\n\nlatency_ms\x18\x04 \x01(\x01\x12\x10\n\x08query_id\x18\x05 \x01(\t\"\x0e\n\x0cStatsRequest\"u\n\rStatsResponse\x12\x15\n\rtotal_vectors\x18\x01 \x01(\x05\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\x12\n\nindex_type\x18\x03 \x01(\t\x12\x13\n\x0bm_parameter\x18\x04 \x01(\x05\x12\x11\n\tef_search\x18\x05 \x01(\x05\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\xf2\x01\n\rSearchService\x12\x34\n\x05\x42uild\x12\x14.search.BuildRequest\x1a\x15.search.BuildResponse\x12\x34\n\x05Query\x12\x14.search.QueryRequest\x1a\x15.search.QueryResponse\x12\x37\n\x08GetStats\x12\x14.search.StatsRequest\x1a\x15.search.StatsResponse\x12<\n\x0bHealthCheck\x12\x15.search.HealthRequest\x1a\x16.search.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUILDREQUEST']._serialized_start=24
  _globals['_BUILDREQUEST']._serialized_end=90
  _globals['_VECTOR']._serialized_start=92
  _globals['_VECTOR']._serialized_end=116
  _globals['_BUILDRESPONSE']._serialized_start=118
  _globals['_BUILDRESPONSE']._serialized_end=190
  _globals['_QUERYREQUEST']._serialized_start=192
  _globals['_QUERYREQUEST']._serialized_end=297
  _globals['_QUERYRESPONSE']._serialized_start=299
  _globals['_QUERYRESPONSE']._serialized_end=407
  _globals['_STATSREQUEST']._serialized_start=409
  _globals['_STATSREQUEST']._serialized_end=423
  _globals['_STATSRESPONSE']._serialized_start=425
  _globals['_STATSRESPONSE']._serialized_end=542
  _globals['_HEALTHREQUEST']._serialized_start=544
  _globals['_HEALTHREQUEST']._serialized_end=559
  _globals['_HEALTHRESPONSE']._serialized_start=561
  _globals['_HEALTHRESPONSE']._serialized_end=610
  _globals['_SEARCHSERVICE']._serialized_start=613
  _globals['_SEARCHSERVICE']._serialized_end=855
# @@protoc_insertion_point(module_scope)
